// 150 Chinese proverbs & sayings with attribution to their original author or classical source.
// Each entry: { zh: 中文, py: pinyin, en: English meaning, author: 作者/出处, dynasty: era }
const PROVERBS = [
  { zh: "知之为知之，不知为不知，是知也。", py: "Zhī zhī wéi zhī zhī, bù zhī wéi bù zhī, shì zhì yě.", en: "To know what you know and know what you do not know — that is true knowledge.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "学而不思则罔，思而不学则殆。", py: "Xué ér bù sī zé wǎng, sī ér bù xué zé dài.", en: "Learning without thought is labor lost; thought without learning is perilous.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "三人行，必有我师焉。", py: "Sān rén xíng, bì yǒu wǒ shī yān.", en: "When three walk together, one of them is bound to be my teacher.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "己所不欲，勿施于人。", py: "Jǐ suǒ bù yù, wù shī yú rén.", en: "Do not impose on others what you do not desire yourself.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "工欲善其事，必先利其器。", py: "Gōng yù shàn qí shì, bì xiān lì qí qì.", en: "A craftsman who wishes to do good work must first sharpen his tools.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "君子坦荡荡，小人长戚戚。", py: "Jūnzǐ tǎn dàngdàng, xiǎorén cháng qīqī.", en: "The noble are calm and at ease; the petty are forever anxious.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "敏而好学，不耻下问。", py: "Mǐn ér hào xué, bù chǐ xià wèn.", en: "Quick to learn and never ashamed to ask those beneath him.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "温故而知新，可以为师矣。", py: "Wēn gù ér zhī xīn, kěyǐ wéi shī yǐ.", en: "Reviewing the old to learn the new — such a one may be a teacher.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "岁寒，然后知松柏之后凋也。", py: "Suì hán, ránhòu zhī sōngbǎi zhī hòu diāo yě.", en: "Only when the year grows cold do we see the pine and cypress are the last to fade.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "德不孤，必有邻。", py: "Dé bù gū, bì yǒu lín.", en: "Virtue is never solitary; it always has neighbors.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "道可道，非常道。", py: "Dào kě dào, fēicháng dào.", en: "The Way that can be spoken is not the eternal Way.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "千里之行，始于足下。", py: "Qiānlǐ zhī xíng, shǐ yú zú xià.", en: "A journey of a thousand li begins beneath one's feet.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "知人者智，自知者明。", py: "Zhī rén zhě zhì, zì zhī zhě míng.", en: "To know others is wisdom; to know oneself is enlightenment.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "上善若水。", py: "Shàng shàn ruò shuǐ.", en: "The highest good is like water.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "天下难事，必作于易；天下大事，必作于细。", py: "Tiānxià nánshì, bì zuò yú yì; tiānxià dàshì, bì zuò yú xì.", en: "All hard things begin with the easy; all great things begin with the small.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "祸兮福之所倚，福兮祸之所伏。", py: "Huò xī fú zhī suǒ yǐ, fú xī huò zhī suǒ fú.", en: "Misfortune is what fortune leans upon; fortune is where misfortune hides.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "知足者富。", py: "Zhīzú zhě fù.", en: "He who knows contentment is rich.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "大巧若拙，大辩若讷。", py: "Dà qiǎo ruò zhuō, dà biàn ruò nè.", en: "Great skill seems clumsy; great eloquence seems halting.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "为之于未有，治之于未乱。", py: "Wéi zhī yú wèi yǒu, zhì zhī yú wèi luàn.", en: "Act before things take shape; govern before disorder arises.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "胜人者有力，自胜者强。", py: "Shèng rén zhě yǒu lì, zì shèng zhě qiáng.", en: "He who conquers others is strong; he who conquers himself is mighty.", author: "老子 Laozi", dynasty: "Spring & Autumn · 《道德经》" },
  { zh: "知己知彼，百战不殆。", py: "Zhī jǐ zhī bǐ, bǎi zhàn bù dài.", en: "Know yourself and know your foe, and in a hundred battles you will never be in peril.", author: "孙子 Sun Tzu", dynasty: "Spring & Autumn · 《孙子兵法》" },
  { zh: "兵者，诡道也。", py: "Bīng zhě, guǐ dào yě.", en: "All warfare is the art of deception.", author: "孙子 Sun Tzu", dynasty: "Spring & Autumn · 《孙子兵法》" },
  { zh: "不战而屈人之兵，善之善者也。", py: "Bù zhàn ér qū rén zhī bīng, shàn zhī shàn zhě yě.", en: "To subdue the enemy without fighting is the supreme excellence.", author: "孙子 Sun Tzu", dynasty: "Spring & Autumn · 《孙子兵法》" },
  { zh: "兵贵神速。", py: "Bīng guì shén sù.", en: "In war, speed is what matters most.", author: "孙子 Sun Tzu", dynasty: "Spring & Autumn · 《孙子兵法》" },
  { zh: "其疾如风，其徐如林。", py: "Qí jí rú fēng, qí xú rú lín.", en: "Swift as the wind, silent as the forest.", author: "孙子 Sun Tzu", dynasty: "Spring & Autumn · 《孙子兵法》" },
  { zh: "上兵伐谋。", py: "Shàng bīng fá móu.", en: "The highest form of warfare is to attack the enemy's strategy.", author: "孙子 Sun Tzu", dynasty: "Spring & Autumn · 《孙子兵法》" },
  { zh: "投之亡地然后存，陷之死地然后生。", py: "Tóu zhī wáng dì ránhòu cún, xiàn zhī sǐ dì ránhòu shēng.", en: "Cast into hopeless ground, the soldier survives; thrown into deadly terrain, he lives.", author: "孙子 Sun Tzu", dynasty: "Spring & Autumn · 《孙子兵法》" },
  { zh: "故善战者，致人而不致于人。", py: "Gù shàn zhàn zhě, zhì rén ér bù zhì yú rén.", en: "The skilled warrior moves the enemy and is not moved by him.", author: "孙子 Sun Tzu", dynasty: "Spring & Autumn · 《孙子兵法》" },
  { zh: "生于忧患，死于安乐。", py: "Shēng yú yōuhuàn, sǐ yú ānlè.", en: "Thriving in hardship, perishing in comfort.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" },
  { zh: "天时不如地利，地利不如人和。", py: "Tiānshí bùrú dìlì, dìlì bùrú rénhé.", en: "Heaven's timing is less than earth's advantage; earth's advantage is less than human harmony.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" },
  { zh: "富贵不能淫，贫贱不能移，威武不能屈。", py: "Fùguì bùnéng yín, pínjiàn bùnéng yí, wēiwǔ bùnéng qū.", en: "Wealth cannot corrupt him, poverty cannot move him, force cannot bend him.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" },
  { zh: "老吾老，以及人之老；幼吾幼，以及人之幼。", py: "Lǎo wú lǎo, yǐ jí rén zhī lǎo; yòu wú yòu, yǐ jí rén zhī yòu.", en: "Honor your elders, then extend it to others'; cherish your young, then cherish others'.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" },
  { zh: "得道多助，失道寡助。", py: "Dé dào duō zhù, shī dào guǎ zhù.", en: "He who follows the Way has many helpers; he who abandons it has few.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" },
  { zh: "民为贵，社稷次之，君为轻。", py: "Mín wéi guì, shèjì cì zhī, jūn wéi qīng.", en: "The people are most precious, the state comes next, the ruler is the lightest.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" },
  { zh: "尽信书，则不如无书。", py: "Jìn xìn shū, zé bùrú wú shū.", en: "To believe everything in books is worse than having no books at all.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" },
  { zh: "鱼，我所欲也；熊掌，亦我所欲也。", py: "Yú, wǒ suǒ yù yě; xióngzhǎng, yì wǒ suǒ yù yě.", en: "Fish I desire, and bear's paw I desire too — but I cannot have both.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" },
  { zh: "吾生也有涯，而知也无涯。", py: "Wú shēng yě yǒu yá, ér zhī yě wú yá.", en: "My life has a limit, but knowledge has none.", author: "庄子 Zhuangzi", dynasty: "Warring States · 《庄子》" },
  { zh: "井蛙不可以语于海。", py: "Jǐng wā bùkěyǐ yǔ yú hǎi.", en: "You cannot speak of the ocean to a frog in a well.", author: "庄子 Zhuangzi", dynasty: "Warring States · 《庄子》" },
  { zh: "相濡以沫，不如相忘于江湖。", py: "Xiāng rú yǐ mò, bùrú xiāng wàng yú jiānghú.", en: "Better to forget one another in the rivers and lakes than to moisten each other with spit.", author: "庄子 Zhuangzi", dynasty: "Warring States · 《庄子》" },
  { zh: "君子之交淡如水。", py: "Jūnzǐ zhī jiāo dàn rú shuǐ.", en: "The friendship of the noble is plain as water.", author: "庄子 Zhuangzi", dynasty: "Warring States · 《庄子》" },
  { zh: "哀莫大于心死。", py: "Āi mò dà yú xīn sǐ.", en: "No sorrow is greater than the death of the heart.", author: "庄子 Zhuangzi", dynasty: "Warring States · 《庄子》" },
  { zh: "鹏之徙于南冥也，水击三千里。", py: "Péng zhī xǐ yú nán míng yě, shuǐ jī sānqiān lǐ.", en: "When the Peng bird journeys to the southern sea, it stirs the waters three thousand li.", author: "庄子 Zhuangzi", dynasty: "Warring States · 《庄子》" },
  { zh: "人固有一死，或重于泰山，或轻于鸿毛。", py: "Rén gù yǒu yī sǐ, huò zhòng yú Tàishān, huò qīng yú hóngmáo.", en: "All men must die; some deaths weigh as Mount Tai, others as a feather.", author: "司马迁 Sima Qian", dynasty: "Han · 《史记》" },
  { zh: "桃李不言，下自成蹊。", py: "Táo lǐ bù yán, xià zì chéng xī.", en: "Peach and plum trees do not speak, yet a path forms beneath them.", author: "司马迁 Sima Qian", dynasty: "Han · 《史记》" },
  { zh: "项庄舞剑，意在沛公。", py: "Xiàng Zhuāng wǔ jiàn, yì zài Pèi gōng.", en: "Xiang Zhuang dances with his sword, but his aim is the Duke of Pei.", author: "司马迁 Sima Qian", dynasty: "Han · 《史记》" },
  { zh: "燕雀安知鸿鹄之志哉？", py: "Yànquè ān zhī hónghú zhī zhì zāi?", en: "How can the swallow and sparrow know the ambition of the swan?", author: "司马迁 Sima Qian", dynasty: "Han · 《史记》" },
  { zh: "智者千虑，必有一失。", py: "Zhì zhě qiān lǜ, bì yǒu yī shī.", en: "Even the wise, in a thousand thoughts, are sure to err once.", author: "司马迁 Sima Qian", dynasty: "Han · 《史记》" },
  { zh: "非淡泊无以明志，非宁静无以致远。", py: "Fēi dànbó wú yǐ míng zhì, fēi níngjìng wú yǐ zhì yuǎn.", en: "Without serenity one cannot clarify one's aims; without calm one cannot reach far.", author: "诸葛亮 Zhuge Liang", dynasty: "Three Kingdoms · 《诫子书》" },
  { zh: "鞠躬尽瘁，死而后已。", py: "Jūgōng jìncuì, sǐ ér hòu yǐ.", en: "Bend to the task with all one's strength, ceasing only in death.", author: "诸葛亮 Zhuge Liang", dynasty: "Three Kingdoms · 《后出师表》" },
  { zh: "勿以恶小而为之，勿以善小而不为。", py: "Wù yǐ è xiǎo ér wéi zhī, wù yǐ shàn xiǎo ér bù wéi.", en: "Do no evil though it be small; neglect no good though it be slight.", author: "刘备 Liu Bei", dynasty: "Three Kingdoms · 《遗诏》" },
  { zh: "老骥伏枥，志在千里。", py: "Lǎo jì fú lì, zhì zài qiānlǐ.", en: "The old steed in its stall still dreams of a thousand li.", author: "曹操 Cao Cao", dynasty: "Han · 《龟虽寿》" },
  { zh: "对酒当歌，人生几何？", py: "Duì jiǔ dāng gē, rénshēng jǐhé?", en: "Wine before us, let us sing — how long, after all, is life?", author: "曹操 Cao Cao", dynasty: "Han · 《短歌行》" },
  { zh: "本是同根生，相煎何太急？", py: "Běn shì tóng gēn shēng, xiāng jiān hé tài jí?", en: "We sprang from the same root — why scorch each other so fiercely?", author: "曹植 Cao Zhi", dynasty: "Three Kingdoms · 《七步诗》" },
  { zh: "天生我材必有用。", py: "Tiān shēng wǒ cái bì yǒu yòng.", en: "Heaven gave me talent, and it must be put to use.", author: "李白 Li Bai", dynasty: "Tang · 《将进酒》" },
  { zh: "长风破浪会有时，直挂云帆济沧海。", py: "Cháng fēng pò làng huì yǒu shí, zhí guà yún fān jì cānghǎi.", en: "A time will come to ride the wind and cleave the waves, hoisting my sail to cross the sea.", author: "李白 Li Bai", dynasty: "Tang · 《行路难》" },
  { zh: "举头望明月，低头思故乡。", py: "Jǔ tóu wàng míng yuè, dī tóu sī gùxiāng.", en: "I lift my head to the bright moon, then bow it, longing for home.", author: "李白 Li Bai", dynasty: "Tang · 《静夜思》" },
  { zh: "抽刀断水水更流，举杯销愁愁更愁。", py: "Chōu dāo duàn shuǐ shuǐ gèng liú, jǔ bēi xiāo chóu chóu gèng chóu.", en: "Draw a blade to cut the stream and it flows on; raise a cup to drown grief and it deepens.", author: "李白 Li Bai", dynasty: "Tang · 《宣州谢朓楼饯别》" },
  { zh: "桃花潭水深千尺，不及汪伦送我情。", py: "Táohuā tán shuǐ shēn qiān chǐ, bùjí Wāng Lún sòng wǒ qíng.", en: "Peach Blossom Pool is a thousand feet deep, yet shallower than Wang Lun's parting love.", author: "李白 Li Bai", dynasty: "Tang · 《赠汪伦》" },
  { zh: "会当凌绝顶，一览众山小。", py: "Huì dāng líng jué dǐng, yī lǎn zhòng shān xiǎo.", en: "I must ascend the very summit and see all other peaks made small.", author: "杜甫 Du Fu", dynasty: "Tang · 《望岳》" },
  { zh: "读书破万卷，下笔如有神。", py: "Dú shū pò wàn juàn, xià bǐ rú yǒu shén.", en: "Read ten thousand scrolls to the binding's break, and the brush moves as if divine.", author: "杜甫 Du Fu", dynasty: "Tang · 《奉赠韦左丞丈》" },
  { zh: "随风潜入夜，润物细无声。", py: "Suí fēng qián rù yè, rùn wù xì wú shēng.", en: "On the wind it steals into the night, moistening all things soft and unheard.", author: "杜甫 Du Fu", dynasty: "Tang · 《春夜喜雨》" },
  { zh: "安得广厦千万间，大庇天下寒士俱欢颜。", py: "Ān dé guǎng shà qiānwàn jiān, dà bì tiānxià hán shì jù huānyán.", en: "Could I but have ten thousand halls to shelter the world's cold scholars in joy.", author: "杜甫 Du Fu", dynasty: "Tang · 《茅屋为秋风所破歌》" },
  { zh: "野火烧不尽，春风吹又生。", py: "Yěhuǒ shāo bù jìn, chūnfēng chuī yòu shēng.", en: "Wildfire cannot burn it all away; the spring wind blows and it grows again.", author: "白居易 Bai Juyi", dynasty: "Tang · 《赋得古原草送别》" },
  { zh: "在天愿作比翼鸟，在地愿为连理枝。", py: "Zài tiān yuàn zuò bǐyì niǎo, zài dì yuàn wéi liánlǐ zhī.", en: "In heaven, twin birds on a single wing; on earth, two branches grown as one.", author: "白居易 Bai Juyi", dynasty: "Tang · 《长恨歌》" },
  { zh: "同是天涯沦落人，相逢何必曾相识。", py: "Tóng shì tiānyá lúnluò rén, xiāngféng hébì céng xiāngshí.", en: "Both of us are wanderers at the world's edge — why must we have met before to feel akin?", author: "白居易 Bai Juyi", dynasty: "Tang · 《琵琶行》" },
  { zh: "春蚕到死丝方尽，蜡炬成灰泪始干。", py: "Chūncán dào sǐ sī fāng jìn, làjù chéng huī lèi shǐ gān.", en: "The silkworm's thread ends only in death; the candle's tears dry only as ash.", author: "李商隐 Li Shangyin", dynasty: "Tang · 《无题》" },
  { zh: "身无彩凤双飞翼，心有灵犀一点通。", py: "Shēn wú cǎi fèng shuāng fēi yì, xīn yǒu língxī yīdiǎn tōng.", en: "Though we lack the phoenix's wings to fly side by side, our hearts beat as one through a single thread.", author: "李商隐 Li Shangyin", dynasty: "Tang · 《无题》" },
  { zh: "夕阳无限好，只是近黄昏。", py: "Xīyáng wúxiàn hǎo, zhǐshì jìn huánghūn.", en: "The setting sun is boundlessly fair, yet dusk is drawing near.", author: "李商隐 Li Shangyin", dynasty: "Tang · 《登乐游原》" },
  { zh: "海内存知己，天涯若比邻。", py: "Hǎinèi cún zhījǐ, tiānyá ruò bǐlín.", en: "If a true friend lives within the seas, the world's far edge is next door.", author: "王勃 Wang Bo", dynasty: "Tang · 《送杜少府之任蜀州》" },
  { zh: "欲穷千里目，更上一层楼。", py: "Yù qióng qiānlǐ mù, gèng shàng yī céng lóu.", en: "To stretch your gaze a thousand li, climb one more storey of the tower.", author: "王之涣 Wang Zhihuan", dynasty: "Tang · 《登鹳雀楼》" },
  { zh: "劝君更尽一杯酒，西出阳关无故人。", py: "Quàn jūn gèng jìn yī bēi jiǔ, xī chū Yáng Guān wú gùrén.", en: "Drink one more cup, I urge you — west of Yang Pass there are no old friends.", author: "王维 Wang Wei", dynasty: "Tang · 《送元二使安西》" },
  { zh: "独在异乡为异客，每逢佳节倍思亲。", py: "Dú zài yìxiāng wéi yì kè, měi féng jiājié bèi sī qīn.", en: "A stranger alone in a strange land, at every festival I long for kin twice over.", author: "王维 Wang Wei", dynasty: "Tang · 《九月九日忆山东兄弟》" },
  { zh: "莫愁前路无知己，天下谁人不识君。", py: "Mò chóu qiánlù wú zhījǐ, tiānxià shéi rén bù shí jūn.", en: "Grieve not that the road ahead lacks friends — who in all the world does not know you?", author: "高适 Gao Shi", dynasty: "Tang · 《别董大》" },
  { zh: "谁言寸草心，报得三春晖。", py: "Shéi yán cùn cǎo xīn, bào dé sān chūn huī.", en: "Who says a blade of grass can repay the warmth of three spring suns?", author: "孟郊 Meng Jiao", dynasty: "Tang · 《游子吟》" },
  { zh: "谁知盘中餐，粒粒皆辛苦。", py: "Shéi zhī pán zhōng cān, lì lì jiē xīnkǔ.", en: "Who knows that of the food on the plate, every grain is born of toil?", author: "李绅 Li Shen", dynasty: "Tang · 《悯农》" },
  { zh: "纸上得来终觉浅，绝知此事要躬行。", py: "Zhǐ shàng dé lái zhōng jué qiǎn, jué zhī cǐ shì yào gōng xíng.", en: "Knowledge from books is shallow in the end; to truly know a thing, you must do it.", author: "陆游 Lu You", dynasty: "Song · 《冬夜读书示子聿》" },
  { zh: "山重水复疑无路，柳暗花明又一村。", py: "Shān chóng shuǐ fù yí wú lù, liǔ àn huā míng yòu yī cūn.", en: "Where hills crowd and streams twist, the path seems gone — then willows shade and flowers bloom on a new village.", author: "陆游 Lu You", dynasty: "Song · 《游山西村》" },
  { zh: "位卑未敢忘忧国。", py: "Wèi bēi wèi gǎn wàng yōu guó.", en: "Though lowly in rank, I never dare forget my care for the nation.", author: "陆游 Lu You", dynasty: "Song · 《病起书怀》" },
  { zh: "人有悲欢离合，月有阴晴圆缺。", py: "Rén yǒu bēi huān lí hé, yuè yǒu yīn qíng yuán quē.", en: "People know sorrow and joy, parting and reunion; the moon knows shadow and light, fullness and wane.", author: "苏轼 Su Shi", dynasty: "Song · 《水调歌头》" },
  { zh: "但愿人长久，千里共婵娟。", py: "Dàn yuàn rén cháng jiǔ, qiānlǐ gòng chánjuān.", en: "May we live long, and share this fair moon though a thousand li apart.", author: "苏轼 Su Shi", dynasty: "Song · 《水调歌头》" },
  { zh: "不识庐山真面目，只缘身在此山中。", py: "Bù shí Lúshān zhēn miànmù, zhǐ yuán shēn zài cǐ shān zhōng.", en: "I cannot see Mount Lu's true face, only because I stand within the mountain.", author: "苏轼 Su Shi", dynasty: "Song · 《题西林壁》" },
  { zh: "竹外桃花三两枝，春江水暖鸭先知。", py: "Zhú wài táohuā sān liǎng zhī, chūn jiāng shuǐ nuǎn yā xiān zhī.", en: "Beyond the bamboo a few peach blossoms; the ducks know first that the spring river warms.", author: "苏轼 Su Shi", dynasty: "Song · 《惠崇春江晚景》" },
  { zh: "生当作人杰，死亦为鬼雄。", py: "Shēng dāng zuò rén jié, sǐ yì wéi guǐ xióng.", en: "In life, be a hero among men; in death, a champion among ghosts.", author: "李清照 Li Qingzhao", dynasty: "Song · 《夏日绝句》" },
  { zh: "莫等闲，白了少年头，空悲切。", py: "Mò děngxián, bái le shàonián tóu, kōng bēi qiè.", en: "Idle not, lest youth's hair turn white and only empty grief remain.", author: "岳飞 Yue Fei", dynasty: "Song · 《满江红》" },
  { zh: "先天下之忧而忧，后天下之乐而乐。", py: "Xiān tiānxià zhī yōu ér yōu, hòu tiānxià zhī lè ér lè.", en: "Be first to worry the world's worries, last to enjoy its joys.", author: "范仲淹 Fan Zhongyan", dynasty: "Song · 《岳阳楼记》" },
  { zh: "等闲识得东风面，万紫千红总是春。", py: "Děngxián shí dé dōngfēng miàn, wàn zǐ qiān hóng zǒng shì chūn.", en: "Once you know the east wind's face, every shade of bloom is spring.", author: "朱熹 Zhu Xi", dynasty: "Song · 《春日》" },
  { zh: "问渠那得清如许？为有源头活水来。", py: "Wèn qú nǎ dé qīng rúxǔ? Wèi yǒu yuántóu huóshuǐ lái.", en: "How does the pond stay so clear? Because living water flows from its source.", author: "朱熹 Zhu Xi", dynasty: "Song · 《观书有感》" },
  { zh: "粉身碎骨浑不怕，要留清白在人间。", py: "Fěn shēn suì gǔ hún bù pà, yào liú qīngbái zài rénjiān.", en: "Though ground to dust and shattered bone, I fear it not — I keep my purity in the world.", author: "于谦 Yu Qian", dynasty: "Ming · 《石灰吟》" },
  { zh: "人生自古谁无死，留取丹心照汗青。", py: "Rénshēng zìgǔ shéi wú sǐ, liú qǔ dānxīn zhào hànqīng.", en: "Since ancient times, who has not died? Let me leave a loyal heart to light the pages of history.", author: "文天祥 Wen Tianxiang", dynasty: "Song · 《过零丁洋》" },
  { zh: "千磨万击还坚劲，任尔东西南北风。", py: "Qiān mó wàn jī hái jiānjìng, rèn ěr dōng xī nán běi fēng.", en: "Ground and struck ten thousand times, it stands firm — let the winds blow from every quarter.", author: "郑板桥 Zheng Banqiao", dynasty: "Qing · 《竹石》" },
  { zh: "落红不是无情物，化作春泥更护花。", py: "Luò hóng bù shì wúqíng wù, huà zuò chūn ní gèng hù huā.", en: "Fallen petals are not heartless things; turned to spring soil, they nurture the flowers anew.", author: "龚自珍 Gong Zizhen", dynasty: "Qing · 《己亥杂诗》" },
  { zh: "海纳百川，有容乃大。", py: "Hǎi nà bǎi chuān, yǒu róng nǎi dà.", en: "The sea takes in a hundred rivers; its greatness lies in its capacity.", author: "林则徐 Lin Zexu", dynasty: "Qing · 联句" },
  { zh: "千里之堤，溃于蚁穴。", py: "Qiānlǐ zhī dī, kuì yú yǐ xué.", en: "A dike of a thousand li collapses from an ant's burrow.", author: "韩非子 Han Feizi", dynasty: "Warring States · 《韩非子》" },
  { zh: "宰相必起于州部，猛将必发于卒伍。", py: "Zǎixiàng bì qǐ yú zhōu bù, měng jiàng bì fā yú zú wǔ.", en: "A minister must rise from the provinces; a fierce general from the ranks.", author: "韩非子 Han Feizi", dynasty: "Warring States · 《韩非子》" },
  { zh: "巧诈不如拙诚。", py: "Qiǎo zhà bùrú zhuō chéng.", en: "Clever deceit is worth less than clumsy honesty.", author: "韩非子 Han Feizi", dynasty: "Warring States · 《韩非子》" },
  { zh: "锲而不舍，金石可镂。", py: "Qiè ér bù shě, jīn shí kě lòu.", en: "Carve without ceasing, and even metal and stone can be engraved.", author: "荀子 Xunzi", dynasty: "Warring States · 《荀子》" },
  { zh: "青，取之于蓝，而青于蓝。", py: "Qīng, qǔ zhī yú lán, ér qīng yú lán.", en: "Blue is drawn from the indigo plant, yet is bluer than the plant itself.", author: "荀子 Xunzi", dynasty: "Warring States · 《荀子》" },
  { zh: "不积跬步，无以至千里。", py: "Bù jī kuǐ bù, wú yǐ zhì qiānlǐ.", en: "Without piling up small steps, you cannot reach a thousand li.", author: "荀子 Xunzi", dynasty: "Warring States · 《荀子》" },
  { zh: "蓬生麻中，不扶而直。", py: "Péng shēng má zhōng, bù fú ér zhí.", en: "Mugwort growing among hemp stands straight without support.", author: "荀子 Xunzi", dynasty: "Warring States · 《荀子》" },
  { zh: "流水不腐，户枢不蠹。", py: "Liúshuǐ bù fǔ, hùshū bù dù.", en: "Running water never stagnates; a door hinge never rots.", author: "吕不韦 Lü Buwei", dynasty: "Qin · 《吕氏春秋》" },
  { zh: "察己则可以知人，察今则可以知古。", py: "Chá jǐ zé kěyǐ zhī rén, chá jīn zé kěyǐ zhī gǔ.", en: "Examine yourself to understand others; examine the present to understand the past.", author: "吕不韦 Lü Buwei", dynasty: "Qin · 《吕氏春秋》" },
  { zh: "失之毫厘，谬以千里。", py: "Shī zhī háolí, miù yǐ qiānlǐ.", en: "An error of a hair's breadth leads a thousand li astray.", author: "司马迁 Sima Qian", dynasty: "Han · 《史记》" },
  { zh: "前事不忘，后事之师。", py: "Qián shì bù wàng, hòu shì zhī shī.", en: "Remembering the past is the teacher of the future.", author: "刘向 Liu Xiang", dynasty: "Han · 《战国策》" },
  { zh: "亡羊补牢，未为迟也。", py: "Wáng yáng bǔ láo, wèi wéi chí yě.", en: "To mend the pen after the sheep is lost is still not too late.", author: "刘向 Liu Xiang", dynasty: "Han · 《战国策》" },
  { zh: "鹬蚌相争，渔翁得利。", py: "Yù bàng xiāng zhēng, yúwēng dé lì.", en: "When snipe and clam grapple, the fisherman wins.", author: "刘向 Liu Xiang", dynasty: "Han · 《战国策》" },
  { zh: "百闻不如一见。", py: "Bǎi wén bùrú yī jiàn.", en: "Hearing a hundred times is not like seeing once.", author: "班固 Ban Gu", dynasty: "Han · 《汉书》" },
  { zh: "水至清则无鱼，人至察则无徒。", py: "Shuǐ zhì qīng zé wú yú, rén zhì chá zé wú tú.", en: "Water too clear holds no fish; a person too exacting keeps no friends.", author: "班固 Ban Gu", dynasty: "Han · 《汉书》" },
  { zh: "精诚所至，金石为开。", py: "Jīngchéng suǒ zhì, jīnshí wéi kāi.", en: "Where utter sincerity reaches, metal and stone split open.", author: "王充 Wang Chong", dynasty: "Han · 《论衡》" },
  { zh: "疾风知劲草，板荡识诚臣。", py: "Jí fēng zhī jìng cǎo, bǎn dàng shí chéng chén.", en: "A fierce wind reveals the sturdy grass; turmoil reveals the loyal minister.", author: "李世民 Li Shimin", dynasty: "Tang · 《赠萧瑀》" },
  { zh: "以铜为镜，可以正衣冠；以人为镜，可以明得失。", py: "Yǐ tóng wéi jìng, kěyǐ zhèng yīguān; yǐ rén wéi jìng, kěyǐ míng déshī.", en: "A bronze mirror sets your dress straight; a mirror of people reveals your gains and faults.", author: "李世民 Li Shimin", dynasty: "Tang · 《旧唐书》" },
  { zh: "勿以善小而不为，勿以恶小而为之。", py: "Wù yǐ shàn xiǎo ér bù wéi, wù yǐ è xiǎo ér wéi zhī.", en: "Neglect no good for being small; commit no evil for being slight.", author: "陈寿 Chen Shou", dynasty: "Jin · 《三国志》" },
  { zh: "士别三日，即更刮目相待。", py: "Shì bié sān rì, jí gèng guāmù xiāng dài.", en: "Part from a scholar three days, and you must look on him with new eyes.", author: "陈寿 Chen Shou", dynasty: "Jin · 《三国志》" },
  { zh: "宁为玉碎，不为瓦全。", py: "Nìng wéi yù suì, bù wéi wǎ quán.", en: "Better a shattered jade than an unbroken tile.", author: "李百药 Li Baiyao", dynasty: "Tang · 《北齐书》" },
  { zh: "近朱者赤，近墨者黑。", py: "Jìn zhū zhě chì, jìn mò zhě hēi.", en: "Near vermilion one reddens; near ink one blackens.", author: "傅玄 Fu Xuan", dynasty: "Jin · 《太子少傅箴》" },
  { zh: "非学无以广才，非志无以成学。", py: "Fēi xué wú yǐ guǎng cái, fēi zhì wú yǐ chéng xué.", en: "Without study, talent cannot broaden; without will, study cannot succeed.", author: "诸葛亮 Zhuge Liang", dynasty: "Three Kingdoms · 《诫子书》" },
  { zh: "一年之计在于春，一日之计在于晨。", py: "Yī nián zhī jì zàiyú chūn, yī rì zhī jì zàiyú chén.", en: "The year's plan lies in spring; the day's plan lies in dawn.", author: "萧绎 Xiao Yi", dynasty: "Liang · 《纂要》" },
  { zh: "落霞与孤鹜齐飞，秋水共长天一色。", py: "Luò xiá yǔ gū wù qí fēi, qiū shuǐ gòng cháng tiān yī sè.", en: "The setting glow and a lone wild duck fly as one; autumn waters and the vast sky share a single hue.", author: "王勃 Wang Bo", dynasty: "Tang · 《滕王阁序》" },
  { zh: "穷且益坚，不坠青云之志。", py: "Qióng qiě yì jiān, bù zhuì qīngyún zhī zhì.", en: "In poverty, grow ever firmer; never let fall your soaring ambition.", author: "王勃 Wang Bo", dynasty: "Tang · 《滕王阁序》" },
  { zh: "近水楼台先得月。", py: "Jìn shuǐ lóutái xiān dé yuè.", en: "The waterside pavilion catches the moon first.", author: "苏麟 Su Lin", dynasty: "Song · 《断句》" },
  { zh: "梅须逊雪三分白，雪却输梅一段香。", py: "Méi xū xùn xuě sān fēn bái, xuě què shū méi yī duàn xiāng.", en: "The plum yields to snow three measures of white, yet snow lacks the plum's fragrance.", author: "卢梅坡 Lu Meipo", dynasty: "Song · 《雪梅》" },
  { zh: "纸上得来终觉浅。", py: "Zhǐ shàng dé lái zhōng jué qiǎn.", en: "What is learned from paper alone is always shallow.", author: "陆游 Lu You", dynasty: "Song · 《冬夜读书示子聿》" },
  { zh: "天下兴亡，匹夫有责。", py: "Tiānxià xīngwáng, pǐfū yǒu zé.", en: "The rise and fall of the realm is every common man's burden.", author: "顾炎武 Gu Yanwu", dynasty: "Ming-Qing · 《日知录》" },
  { zh: "书到用时方恨少。", py: "Shū dào yòng shí fāng hèn shǎo.", en: "Only when knowledge is needed do we regret how little we read.", author: "陆游 Lu You", dynasty: "Song · 联句" },
  { zh: "横眉冷对千夫指，俯首甘为孺子牛。", py: "Héng méi lěng duì qiān fū zhǐ, fǔshǒu gān wéi rúzǐ niú.", en: "Brows raised, I face a thousand accusers cold; head bowed, I gladly serve as the children's ox.", author: "鲁迅 Lu Xun", dynasty: "Modern · 《自嘲》" },
  { zh: "其实地上本没有路，走的人多了，也便成了路。", py: "Qíshí dìshàng běn méiyǒu lù, zǒu de rén duō le, yě biàn chéng le lù.", en: "There was no road on the earth; where many walk, a road is made.", author: "鲁迅 Lu Xun", dynasty: "Modern · 《故乡》" },
  { zh: "横眉冷对，俯首甘为。", py: "Héng méi lěng duì, fǔshǒu gān wéi.", en: "Defiant before the cruel, humble before the weak.", author: "鲁迅 Lu Xun", dynasty: "Modern" },
  { zh: "面朝大海，春暖花开。", py: "Miàn cháo dàhǎi, chūn nuǎn huā kāi.", en: "Facing the sea, with spring warmth and blossoming flowers.", author: "海子 Haizi", dynasty: "Modern · 《面朝大海》" },
  { zh: "黑夜给了我黑色的眼睛，我却用它寻找光明。", py: "Hēiyè gěi le wǒ hēisè de yǎnjīng, wǒ què yòng tā xúnzhǎo guāngmíng.", en: "The dark night gave me dark eyes, yet with them I search for the light.", author: "顾城 Gu Cheng", dynasty: "Modern · 《一代人》" },
  { zh: "玉不琢，不成器；人不学，不知义。", py: "Yù bù zhuó, bù chéng qì; rén bù xué, bù zhī yì.", en: "Unpolished jade makes no vessel; an untaught person knows no righteousness.", author: "《礼记》 Book of Rites", dynasty: "Warring States · 《礼记·学记》" },
  { zh: "凡事预则立，不预则废。", py: "Fán shì yù zé lì, bù yù zé fèi.", en: "In all things, preparation brings success; without it, ruin.", author: "《礼记》 Book of Rites", dynasty: "Warring States · 《礼记·中庸》" },
  { zh: "独学而无友，则孤陋而寡闻。", py: "Dú xué ér wú yǒu, zé gūlòu ér guǎ wén.", en: "To study alone without companions leaves one ignorant and ill-informed.", author: "《礼记》 Book of Rites", dynasty: "Warring States · 《礼记·学记》" },
  { zh: "大道之行也，天下为公。", py: "Dà dào zhī xíng yě, tiānxià wéi gōng.", en: "When the Great Way prevails, the world belongs to all.", author: "《礼记》 Book of Rites", dynasty: "Warring States · 《礼记·礼运》" },
  { zh: "满招损，谦受益。", py: "Mǎn zhāo sǔn, qiān shòu yì.", en: "Arrogance invites loss; humility brings gain.", author: "《尚书》 Book of Documents", dynasty: "Zhou · 《尚书·大禹谟》" },
  { zh: "天行健，君子以自强不息。", py: "Tiān xíng jiàn, jūnzǐ yǐ zìqiáng bù xī.", en: "Heaven moves with vigor; the noble strive without ceasing.", author: "《周易》 Book of Changes", dynasty: "Zhou · 《周易·乾》" },
  { zh: "地势坤，君子以厚德载物。", py: "Dìshì kūn, jūnzǐ yǐ hòudé zài wù.", en: "Earth's nature is yielding; the noble bear all things with ample virtue.", author: "《周易》 Book of Changes", dynasty: "Zhou · 《周易·坤》" },
  { zh: "穷则变，变则通，通则久。", py: "Qióng zé biàn, biàn zé tōng, tōng zé jiǔ.", en: "At an impasse, change; change brings passage; passage brings endurance.", author: "《周易》 Book of Changes", dynasty: "Zhou · 《周易·系辞》" },
  { zh: "他山之石，可以攻玉。", py: "Tā shān zhī shí, kěyǐ gōng yù.", en: "Stones from another hill can polish your jade.", author: "《诗经》 Book of Songs", dynasty: "Zhou · 《诗经·小雅》" },
  { zh: "投我以桃，报之以李。", py: "Tóu wǒ yǐ táo, bào zhī yǐ lǐ.", en: "Give me a peach, and I return a plum.", author: "《诗经》 Book of Songs", dynasty: "Zhou · 《诗经·大雅》" },
  { zh: "靡不有初，鲜克有终。", py: "Mí bù yǒu chū, xiǎn kè yǒu zhōng.", en: "All things have a beginning, but few see them through to the end.", author: "《诗经》 Book of Songs", dynasty: "Zhou · 《诗经·大雅》" },
  { zh: "言者无罪，闻者足戒。", py: "Yán zhě wú zuì, wén zhě zú jiè.", en: "Let the speaker bear no blame, and the listener take due warning.", author: "《诗经》 Book of Songs", dynasty: "Zhou · 《诗经·大序》" },
  { zh: "知者不惑，仁者不忧，勇者不惧。", py: "Zhì zhě bù huò, rén zhě bù yōu, yǒng zhě bù jù.", en: "The wise are free of doubt, the kind of worry, the brave of fear.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "君子和而不同，小人同而不和。", py: "Jūnzǐ hé ér bù tóng, xiǎorén tóng ér bù hé.", en: "The noble harmonize without conforming; the petty conform without harmony.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "欲速则不达，见小利则大事不成。", py: "Yù sù zé bù dá, jiàn xiǎo lì zé dàshì bù chéng.", en: "Haste prevents arrival; chasing small gains ruins great deeds.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "人无远虑，必有近忧。", py: "Rén wú yuǎn lǜ, bì yǒu jìn yōu.", en: "Without thought for the distant, trouble is always near.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "过而不改，是谓过矣。", py: "Guò ér bù gǎi, shì wèi guò yǐ.", en: "To err and not amend — that is the real error.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "君子求诸己，小人求诸人。", py: "Jūnzǐ qiú zhū jǐ, xiǎorén qiú zhū rén.", en: "The noble demand of themselves; the petty demand of others.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "志士仁人，无求生以害仁，有杀身以成仁。", py: "Zhìshì rénrén, wú qiú shēng yǐ hài rén, yǒu shā shēn yǐ chéng rén.", en: "The resolute and humane will not save their lives at virtue's cost, but will give their lives to fulfill it.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "四海之内皆兄弟也。", py: "Sì hǎi zhī nèi jiē xiōngdì yě.", en: "Within the four seas, all men are brothers.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "知者乐水，仁者乐山。", py: "Zhì zhě yào shuǐ, rén zhě yào shān.", en: "The wise delight in water; the kind delight in mountains.", author: "孔子 Confucius", dynasty: "Spring & Autumn · 《论语》" },
  { zh: "得民心者得天下。", py: "Dé mín xīn zhě dé tiānxià.", en: "He who wins the hearts of the people wins all under heaven.", author: "孟子 Mencius", dynasty: "Warring States · 《孟子》" }
];
